---
variables:
  DUNECI_OPTS: "/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts"

before_script:
  - duneci-install-module https://gitlab.dune-project.org/core/dune-common.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-geometry.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-grid.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-istl.git
  - duneci-install-module https://gitlab.dune-project.org/core/dune-localfunctions.git
  - duneci-install-module https://gitlab.dune-project.org/extensions/dune-alugrid.git
  - duneci-install-module https://gitlab.dune-project.org/extensions/dune-spgrid.git

# debian:9--gcc:
#   image: duneci/base:9
#   script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

# debian:9--clang:
#   image: duneci/base:9
#   script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-clang.opts

# debian:8--gcc:
#   image: duneci/base:8
#   script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

#debian:8-backports--clang:
#  image: duneci/base:8-backports
#  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-clang.opts

# ubuntu:16.04--gcc:
#   image: duneci/base:16.04
#   script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

# ubuntu:16.04--clang:
#   image: duneci/base:16.04
#   script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-clang.opts

# debian:9--gcc--petsc:
#   image: martinnolte/duneci-petsc:9
#   script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

debian:9--gcc-O2--petsc:
  image: martinnolte/duneci-petsc:9
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc-O.opts

debian:9--gcc-g--petsc:
  image: martinnolte/duneci-petsc:9
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc-g.opts
