---
variables:
  DUNECI_OPTS: "/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts"

#before_script:
#  - duneci-install-module https://gitlab.dune-project.org/extensions/dune-alugrid.git
#  - duneci-install-module https://gitlab.dune-project.org/extensions/dune-spgrid.git

.base: &base
  stage: test
  when: always
  tags:
    - "stuttgart"

# FEM_REQUIRE_PETSC=force is intended to trigger an error during cmake
# configuration if PETSc is not found
.base-petsc: &base-petsc
  <<: *base
  variables:
    FEM_REQUIRE_PETSC: "force"

# FEM_REQUIRE_PETSC=disable is intended force PETSc to not being found
.base-nopetsc: &base-nopetsc
  <<: *base
  variables:
    FEM_REQUIRE_PETSC: "disable"

# available image tags,
# debian-9-gcc-6-14
# debian-10-gcc-7-14
# debian-10-gcc-8-17
# debian-10-gcc-8-noassert-17
# debian-10-clang-6-libcpp-17 <-- this one does not seem to work
# ubuntu-18.04-clang-6-17
#
# We reserve some jobs for the nightly build. The Gitlab-schedule for
# the nightly build will also set the environment variable
# TORTURE_TESTS=on

debian-9-gcc-6-14:
  <<: *base-petsc
  image: dune-fem-ci:2.6-debian-9-gcc-6-14
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

debian-10-gcc-7-14:
  <<: *base-petsc
  image: dune-fem-ci:2.6-debian-10-gcc-7-14
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc7.opts

debian-10-gcc-8-17:
  <<: *base-petsc
  image: dune-fem-ci:2.6-debian-10-gcc-8-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts
  only:
    - triggers
    - schedules

debian-10-gcc-8-noassert-17:
  <<: *base-petsc
  image: dune-fem-ci:2.6-debian-10-gcc-8-noassert-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts
  only:
    - triggers
    - schedules

# This fails, have to further investigate what this libcpp really means.
.debian-10-clang-6-libcpp-17:
  <<: *base-petsc
  image: dune-fem-ci:2.6-debian-10-clang-6-libcpp-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-clang-6.opts
  only:
    - triggers
    - schedules

ubuntu-18.04-clang-6-17:
  <<: *base-petsc
  image: dune-fem-ci:2.6-ubuntu-18.04-clang-6-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-clang.opts

####################### REQUIRE_PETSc=disable versions ########################
#
# We only test Debian 10 as we basically only want to test whether the
# build-system successfully has disabled the PETSc bindings.

debian-10-gcc-7-14-nopetsc:
  <<: *base-nopetsc
  image: dune-fem-ci:2.6-debian-10-gcc-7-14
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc7.opts

debian-10-gcc-8-17-petsc:
  <<: *base-nopetsc
  image: dune-fem-ci:2.6-debian-10-gcc-8-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts
  only:
    - triggers
    - schedules

debian-10-gcc-8-noassert-17-nopetsc:
  <<: *base-nopetsc
  image: dune-fem-ci:2.6-debian-10-gcc-8-noassert-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts
  only:
    - triggers
    - schedules
