---
variables:
  DUNECI_OPTS: "/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts"

before_script:
  - duneci-install-module https://gitlab.dune-project.org/extensions/dune-alugrid.git
  - duneci-install-module https://gitlab.dune-project.org/extensions/dune-spgrid.git

.base: &base
  tags:
    - "stuttgart"

# available image tags,
# debian-9-gcc-6-14
# debian-10-gcc-7-14
# debian-10-gcc-8-17
# debian-10-gcc-8-noassert-17
# debian-10-clang-6-libcpp-17
# ubuntu-18.04-clang-6-17

debian-9-gcc-6-14:
  <<: *base
  image: dune-fem-ci:git-debian-9-gcc-6-14
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

debian-10-gcc-7-14:
  <<: *base
  image: dune-fem-ci:git-debian-10-gcc-7-14
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc7.opts

debian-10-gcc-8-17:
  <<: *base
  image: dune-fem-ci:git-debian-10-gcc-8-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

debian-10-gcc-8-noassert-17:
  <<: *base
  image: dune-fem-ci:git-debian-10-gcc-8-noassert-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

debian-10-clang-6-libcpp-17:
  <<: *base
  image: dune-fem-ci:git-debian-10-clang-6-libcpp-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-clang.opts

ubuntu-18.04-clang-6-17:
  <<: *base
  image: dune-fem-ci:git-ubuntu-18.04-clang-6-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-clang.opts

####################### PETSc versions ########################

debian-9-gcc-6-14-petsc:
  <<: *base
  image: dune-fem-ci:git-debian-9-gcc-6-14-petsc
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

debian-10-gcc-7-14-petsc:
  <<: *base
  image: dune-fem-ci:git-debian-10-gcc-7-14-petsc
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc7.opts

debian-10-gcc-8-17-petsc:
  <<: *base
  image: dune-fem-ci:git-debian-10-gcc-8-17-petsc
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

debian-10-gcc-8-noassert-17-petsc:
  <<: *base
  image: dune-fem-ci:git-debian-10-gcc-8-noassert-17-petsc
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

debian-10-clang-6-libcpp-17-petsc:
  <<: *base
  image: dune-fem-ci:git-debian-10-clang-6-libcpp-17-petsc
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-clang.opts

ubuntu-18.04-clang-6-17-petsc:
  <<: *base
  image: dune-fem-ci:git-ubuntu-18.04-clang-6-17-petsc
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-clang.opts





ubuntu-18.04-clang-6-17-petsc-torture:
  <<: *base
  image: dune-fem-ci:git-ubuntu-18.04-clang-6-17-petsc
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-clang.opts
  when: always
  only:
    - triggers
    - schedules
