---
variables:
  DUNECI_OPTS: "/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts"

before_script:
  - duneci-install-module https://gitlab.dune-project.org/extensions/dune-alugrid.git
  - duneci-install-module https://gitlab.dune-project.org/extensions/dune-spgrid.git

debian-10-gcc-7-14:
  image: registry.dune-project.org/docker/ci/dune:git-debian-10-gcc-7-14
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc7.opts

debian-9-gcc-6-14:
  image: registry.dune-project.org/docker/ci/dune:git-debian-9-gcc-6-14
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

debian-10-gcc-8-17:
  image: registry.dune-project.org/docker/ci/dune:git-debian-10-gcc-8-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

debian-10-gcc-8-noassert-17:
  image: registry.dune-project.org/docker/ci/dune:git-debian-10-gcc-8-noassert-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

debian-10-clang-6-libcpp-17:
  image: registry.dune-project.org/docker/ci/dune:git-debian-10-clang-6-libcpp-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-clang.opts

ubuntu-18.04-clang-6-17:
  image: registry.dune-project.org/docker/ci/dune:git-ubuntu-18.04-clang-6-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-clang.opts

debian:9--gcc--petsc:
  image: registry.dune-project.org/dune-fem/dune-fem/ci-petsc:9
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-gcc.opts

ubuntu-18.04-clang-6-17-torture:
  image: registry.dune-project.org/docker/ci/dune:git-ubuntu-18.04-clang-6-17
  script: duneci-standard-test --opts=/builds/dune-fem/dune-fem/scripts/opts/ci-clang.opts
  when: always
  only:
    - triggers
    - schedules
