[build-system]
requires = ['dune-grid>=2.8.0.dev0', 'mpi4py', 'matplotlib', 'scipy', 'fenics-ufl==2019.1.0', 'dune-alugrid>=2.8.0.dev0', 'dune-istl>=2.8.0.dev0', 'dune-localfunctions>=2.8.0.dev0']
build-backend = 'setuptools.build_meta'
